---
- name: Install common packages
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-pip
    - supervisor

- name: Create user
  user:
    name: '{{ service_user }}'
    home: '{{ service_home }}'
    createhome: yes
    state: present

