---

- name: 'Ensure directory'
  file: 
    path: '{{ service_home }}/{{ service_name }}'
    state: directory
    owner: '{{ service_user }}'

- name: 'Copy the service'
  copy:
    src: 'files/{{ service_name }}/'
    dest: '{{ service_home }}/{{ service_name }}'
    owner: '{{ service_user }}'

- name: 'Install dependencies'
  command: 'pip install -r {{ service_home }}/{{ service_name }}/require.txt'
  
- name: 'Copy supervisor template'
  template: 
    src: 'files/service.conf.j2'
    dest: '/etc/supervisor/conf.d/{{ service_name }}.conf'
    owner: root

- name: 'Restart supervisor'
  service: name=supervisor state=restarted

- name: 'Restart service'
  supervisorctl: name='{{ service_name }}' state=restarted

